trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Free Trial(a2fa597b-f361-4e1e-9c15-78d9462a3d39)'
    azureContainerRegistry: '{"loginServer":"sampleregistry123.azurecr.io", "id" : "/subscriptions/a2fa597b-f361-4e1e-9c15-78d9462a3d39/resourceGroups/ABCD/providers/Microsoft.ContainerRegistry/registries/sampleregistry123"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'run'